# Generated by Django 3.2.7 on 2021-09-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210923_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.CharField(max_length=100),
        ),
    ]
