# Generated by Django 3.2.7 on 2021-09-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_league_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league_id',
        ),
    ]
