# Generated by Django 3.2.7 on 2021-09-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_team_league_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
