# Generated by Django 3.2.7 on 2021-09-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210924_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='self',
            new_name='selfurl',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='self',
            new_name='selfurl',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='self',
            new_name='selfurl',
        ),
    ]
