# Generated by Django 3.2.7 on 2021-09-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210924_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='selfurl',
            new_name='self',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='selfurl',
            new_name='self',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='selfurl',
            new_name='self',
        ),
    ]
