# Generated by Django 3.2.6 on 2021-09-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210924_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='selfurl',
            new_name='self',
        ),
    ]
