# Generated by Django 3.2.6 on 2021-09-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_selfurl_team_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='selfurl',
            new_name='self',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='selfurl',
            new_name='self',
        ),
    ]
