# Generated by Django 3.2.7 on 2021-09-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210925_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'League', 'verbose_name_plural': 'League'},
        ),
    ]
