# Generated by Django 3.2.7 on 2021-09-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_league_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='self_name',
            field=models.CharField(db_column='self', max_length=100),
        ),
    ]
