# Generated by Django 3.2.7 on 2021-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_league_self_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Player'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='self',
            new_name='self_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='self',
            new_name='self_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
