# Generated by Django 3.2.7 on 2021-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210925_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='times_trained',
            field=models.IntegerField(max_length=100),
        ),
    ]
