# Generated by Django 3.2.7 on 2021-10-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_player_self_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='self_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='times_trained',
            field=models.IntegerField(max_length=100),
        ),
    ]
