# Generated by Django 3.2.7 on 2021-10-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20211001_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_name',
            field=models.CharField(db_column='self', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='self_name',
            field=models.CharField(db_column='self', max_length=100),
        ),
    ]
